services:
  app:
    build: .
    volumes:
      - /data:/data:ro
      - ./src:/app
      - ./data.json:/app/data.json:ro
    entrypoint: python3 /app/main.py
    env_file:
      - .env
    networks:
      - database_network



networks:
  database_network:
    external: true
